---
meta:
  az: (( param "What availability zone is SHIELD deployed to?" ))

resource_pools:
- name:     small
  network:  shield
  stemcell: (( grab meta.stemcell ))

  cloud_properties:
    instance_type: m3.medium
    availability_zone: (( grab meta.az ))
    ephemeral_disk:
      size: 4096
      type: gp2


compilation:
  network: shield
  reuse_compilation_vms: true
  workers: 4

  cloud_properties:
    instance_type: m3.large
    availability_zone: (( grab meta.az ))
    ephemeral_disk:
      size: 8192
      type: gp2


jobs:
- name: shield
  resource_pool: small
